import os
from bs4 import BeautifulSoup

# Define the path to the book file generated by Jekyll.
# This script assumes you run it from your project's root directory.
file_path = '_site/book.html'

def count_characters_in_html(file_path):
    """
    Reads an HTML file, strips all HTML tags, and counts the
    number of characters in the remaining plain text.
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            html_content = file.read()

        # Use BeautifulSoup to parse the HTML
        soup = BeautifulSoup(html_content, 'html.parser')

        # Get all the text from the document, with HTML tags stripped
        # This also includes whitespace and newlines between tags.
        plain_text = soup.get_text()

        # Calculate the number of characters
        character_count = len(plain_text)

        return character_count

    except FileNotFoundError:
        return f"Error: The file was not found at '{file_path}'. Please run 'jekyll build' first."
    except Exception as e:
        return f"An error occurred: {e}"

# --- Main execution ---
if __name__ == "__main__":
    if not os.path.exists(file_path):
        print(f"Error: The file was not found at '{file_path}'.")
        print("Please run 'jekyll build' to generate the site first.")
    else:
        book_character_count = count_characters_in_html(file_path)
        if isinstance(book_character_count, int):
            # Using a formatted string to make the output clear
            print(f"✅ Success! The total character count of the book is: {book_character_count:,}")
        else:
            # Print any error messages
            print(book_character_count)
