# Gemfile
source "https://rubygems.org"

# Use the latest version of Jekyll
gem "jekyll"

# Plugins needed for your site
group :jekyll_plugins do
  gem "jekyll-remote-theme"
  gem "jekyll-feed"
  gem "jekyll-archives"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
